# Generated by Django 4.2.8 on 2023-12-28 09:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255, verbose_name="Марка авто")),
            ],
            options={
                "verbose_name": "Марка",
                "verbose_name_plural": "Марки",
            },
        ),
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "licence_plate",
                    models.CharField(
                        max_length=255, verbose_name="Реєстраційний номер"
                    ),
                ),
                (
                    "number_of_seats",
                    models.IntegerField(verbose_name="Кількість місць"),
                ),
            ],
            options={
                "verbose_name": "Автобус",
                "verbose_name_plural": "Автобуси",
            },
        ),
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Номер телефону"
                    ),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="E-mail")),
            ],
            options={
                "verbose_name": "Покупець",
                "verbose_name_plural": "Покупці",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255, verbose_name="Місто")),
                ("region", models.CharField(max_length=255, verbose_name="Область")),
                ("country", models.CharField(max_length=255, verbose_name="Країна")),
            ],
            options={
                "verbose_name": "Місто",
                "verbose_name_plural": "Міста",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Назва компанії"),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Перевізник",
                "verbose_name_plural": "Перевізники",
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Партнер",
                "verbose_name_plural": "Партнери",
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station", models.CharField(max_length=255, verbose_name="Станція")),
                (
                    "street_type",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Вулиця/Провулок...."
                    ),
                ),
                (
                    "street",
                    models.CharField(max_length=255, null=True, verbose_name="Назва"),
                ),
                ("number", models.IntegerField(null=True)),
            ],
            options={
                "verbose_name": "Станція",
                "verbose_name_plural": "Станції",
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timedate_departure",
                    models.DateTimeField(verbose_name="Час/Дата відправки"),
                ),
                (
                    "timedate_arrival",
                    models.DateTimeField(verbose_name="Час/Дата приїзду"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.IntegerField(verbose_name="Ціна")),
                (
                    "arrival_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arrival_station",
                        to="core.station",
                        verbose_name="Станція приїзду",
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.bus",
                        verbose_name="Автобус",
                    ),
                ),
                (
                    "departure_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departure_station",
                        to="core.station",
                        verbose_name="Станція відправки",
                    ),
                ),
                (
                    "end_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="end_point_city",
                        to="core.city",
                        verbose_name="Точка призначення",
                    ),
                ),
                (
                    "start_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="start_point_city",
                        to="core.city",
                        verbose_name="Місто відправки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подорож",
                "verbose_name_plural": "Подорожі",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Ім'я")),
                ("last_name", models.CharField(max_length=255, verbose_name="Фамілія")),
                (
                    "purchase_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата покупки"
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.trip",
                        verbose_name="Поездка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Білет",
                "verbose_name_plural": "Білети",
            },
        ),
    ]
