# Generated by Django 5.0 on 2023-12-22 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="arrival_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="arrival_station",
                to="core.station",
                verbose_name="Станція приїзду",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="bus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.bus",
                verbose_name="Автобус",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="departure_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departure_station",
                to="core.station",
                verbose_name="Станція відправки",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="end_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="end_point_city",
                to="core.city",
                verbose_name="Точка назначения",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="start_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="start_point_city",
                to="core.city",
                verbose_name="Город отправки",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.trip",
                verbose_name="Поездка",
            ),
        ),
    ]
