# Generated by Django 4.2.8 on 2023-12-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="licence_plate",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Реєстраційний номер"
            ),
        ),
    ]
