# Generated by Django 4.2.8 on 2023-12-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_bus_licence_plate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="brand",
            field=models.CharField(max_length=255, verbose_name="Марка"),
        ),
        migrations.DeleteModel(
            name="Brand",
        ),
    ]
