# Generated by Django 4.2.8 on 2023-12-25 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_trip_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="buyer",
        ),
    ]
