# Generated by Django 4.2.8 on 2024-01-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_bus_brand_delete_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="returned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bus",
            name="brand",
            field=models.CharField(max_length=255, verbose_name="Опис"),
        ),
    ]
