# Generated by Django 4.2.8 on 2024-01-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_ticket_returned_alter_bus_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="payed",
            field=models.BooleanField(default=False),
        ),
    ]
