# Generated by Django 4.2.8 on 2024-01-15 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_ticket_payed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="payed",
        ),
    ]
