# Generated by Django 4.2.8 on 2024-01-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_ticket_payed"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="sub_account",
            field=models.BooleanField(default=False, verbose_name="Суб-акаунт"),
        ),
    ]
