# Generated by Django 4.2.8 on 2024-01-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_partner_sub_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="sub_account",
        ),
        migrations.AddField(
            model_name="partner",
            name="is_sub_account",
            field=models.BooleanField(default=False, verbose_name="Суб-аккаунт"),
        ),
    ]
