# Generated by Django 4.2.8 on 2024-01-15 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_partner_sub_account_partner_is_sub_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="is_sub_account",
        ),
    ]
