# Generated by Django 4.2.8 on 2024-02-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_partner_is_sub_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
